FROM kkarczmarczyk/node-yarn:6.9-slim

MAINTAINER Jeromy Maligie <jmaligie@gmail.com>

# Global install flow requirements
RUN apt-get update && apt-get install -y ocaml libelf-dev

WORKDIR /workspace
