FROM kkarczmarczyk/node-yarn:7.5-wheezy

MAINTAINER Jeromy Maligie <jmaligie@gmail.com>

# Global install flow requirements
RUN apt-get update && apt-get install -y ocaml libelf-dev

WORKDIR /workspace
